### ISSUE TITLE
n00b errorr

### ISSUE THREAD

**Issue by jayunit100** [sarun87/k8snetlook#14]
```
➜  k8snetlook git:(master) ✗ ./k8snetlook-osx pod -srcpodname xa-5c564f47d6-g2lrf -srcpodns x -dstpodname yb-ff9944c98-99lg4  -dstpodns y  --config=/Users/jayunit100/.kube/config

src pod container id: containerd://3baa1bad12b25c8859fad10d57a41fed6b84f2e90dcb4961ffa34cde365cc872
Unable to fetch netns handle for pod xa-5c564f47d6-g2lrf. Error: not implemented Exiting..
```

**Comment by sarun87** [comment]
Yeah. The tool needs to be executed on the node ion which the source Pod is running. This is listed here: https://github.com/sarun87/k8snetlook#caveats

Also the darwin target `k8snetlook-osx` is mainly there for development & unit testing purposes. It doesn't do any real debugging.

**Comment by jayunit100** [comment]
I think the new Docker packaging will solve this bc the cli can just fire off a k8s job yaml

**Comment by sarun87** [comment]
Ah interesting thought. The CLI can run `kubectl apply` after performing any necessary substitutions in the yaml spec.
@jayunit100 do I sense an PR coming? ;-)

**Comment by sarun87** [comment]
Closed by https://github.com/sarun87/k8snetlook/pull/20
